pub const ENV_VAR_PREFIX: &str = "CW_";

// Meta / runtime control
pub const ENV_ALLOW_ENV_OVERRIDE: &str = "CW_ALLOW_ENV_OVERRIDE";
pub const ENV_CI_CONFIG: &str = "CW_CI_CONFIG";
pub const ENV_IGNORE_CONFIG_FILE: &str = "CW_IGNORE_CONFIG_FILE";
pub const ENV_DEFAULT_BRANCH: &str = "CW_DEFAULT_BRANCH";

// Registry (SRS §6)
pub const ENV_REGISTRY_URL: &str = "CW_REGISTRY_URL";
pub const ENV_REGISTRY_REF: &str = "CW_REGISTRY_REF";
pub const ENV_REGISTRY_SECTION: &str = "CW_REGISTRY_SECTION";

// Commit (SRS §7)
pub const ENV_COMMIT_SUBJECT_MAX_LENGTH: &str = "CW_COMMIT_SUBJECT_MAX_LENGTH";
pub const ENV_COMMIT_SCOPES_MODE: &str = "CW_COMMIT_SCOPES_MODE";
pub const ENV_COMMIT_SCOPES_RESTRICT_TO_DEFINED: &str = "CW_COMMIT_SCOPES_RESTRICT_TO_DEFINED";
pub const ENV_COMMIT_TICKET_REQUIRED: &str = "CW_COMMIT_TICKET_REQUIRED";
pub const ENV_COMMIT_TICKET_PATTERN: &str = "CW_COMMIT_TICKET_PATTERN";
pub const ENV_COMMIT_TICKET_SOURCE: &str = "CW_COMMIT_TICKET_SOURCE";

// Branch (SRS §8)
pub const ENV_BRANCH_REMOTE: &str = "CW_BRANCH_REMOTE";
pub const ENV_BRANCH_PROTECTED: &str = "CW_BRANCH_PROTECTED";
pub const ENV_BRANCH_NAMING_PATTERN: &str = "CW_BRANCH_NAMING_PATTERN";

// PR (SRS §9)
pub const ENV_PR_TITLE_REQUIRE_CONVENTIONAL: &str = "CW_PR_TITLE_REQUIRE_CONVENTIONAL";
pub const ENV_PR_TITLE_REQUIRE_TICKET: &str = "CW_PR_TITLE_REQUIRE_TICKET";
pub const ENV_PR_TITLE_SCOPE_MODE: &str = "CW_PR_TITLE_SCOPE_MODE";
pub const ENV_PR_BRANCH_SOURCE_PATTERN: &str = "CW_PR_BRANCH_SOURCE_PATTERN";
pub const ENV_PR_BRANCH_TARGET_ALLOWED: &str = "CW_PR_BRANCH_TARGET_ALLOWED";

// Check (SRS §7 / policy)
pub const ENV_CHECK_REQUIRE_CONVENTIONAL: &str = "CW_CHECK_REQUIRE_CONVENTIONAL";
pub const ENV_CHECK_COMMITS_ENABLED: &str = "CW_CHECK_COMMITS_ENABLED";
pub const ENV_CHECK_COMMITS_ENFORCE_ON: &str = "CW_CHECK_COMMITS_ENFORCE_ON";

// Push (SRS §10)
pub const ENV_PUSH_ALLOW_PROTECTED: &str = "CW_PUSH_ALLOW_PROTECTED";
pub const ENV_PUSH_ALLOW_FORCE: &str = "CW_PUSH_ALLOW_FORCE";
pub const ENV_PUSH_CHECK_COMMITS: &str = "CW_PUSH_CHECK_COMMITS";
pub const ENV_PUSH_CHECK_BRANCH_POLICY: &str = "CW_PUSH_CHECK_BRANCH_POLICY";

// Versioning (SRS §11)
pub const ENV_VERSIONING_TAG_PREFIX: &str = "CW_VERSIONING_TAG_PREFIX";
