site_name: Commit Wizard
site_url: https://commit-wizard.kitechsoftware.com/
repo_url: https://github.com/kitechsoftware/commit-wizard
repo_name: kitechsoftware/commit-wizard

docs_dir: pages

theme:
  name: dracula
  logo: assets/img/icon.png
  favicon: assets/img/icon.png
  highlight_js: highlight.min.js
  highlight_css: atom-one-dark.min.css

nav:
  - Home: index.md
  - Commands:
    - Global Flags: commands/global-flags.md
    - add: commands/add.md
    - bump: commands/bump.md
    - check: commands/check.md
    - commit: commands/commit.md
    - config: commands/config.md
    - doctor: commands/doctor.md
    - init: commands/init.md
    - push: commands/push.md
    - tag: commands/tag.md
  - Guides:
    - Getting Started: guides/getting-started.md
    - Public API Reference: guides/public-api.md
    - Registry System: guides/registry-system.md
    - Configuration:
      - Recommended: guides/configs/recommended.md
      - Minimal: guides/configs/minimal.md
      - Standard: guides/configs/standard.md
      - Full Reference: guides/configs/full.md
      - With Rules: guides/configs/with-rules.md
      - With Registry: guides/configs/with-registry.md

