name: Stability Flow Create Branch

on:
  workflow_dispatch:
    inputs:
      branch_type:
        description: Branch to create
        required: true
        default: release
        type: choice
        options:
          - release
          - hotfix
          - sync
      source_branch:
        description: Source branch to branch from (release only)
        required: false
        default: develop
        type: string
      identifier:
        description: Version or suffix
        required: false
        type: string
      auto_version_bump:
        description: Calculate version automatically
        required: true
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  next-version:
    if: ${{ inputs.branch_type != 'hotfix' }}
    uses: KiTechSoftware/stability-flow/.github/workflows/next-version.yml@main
    with:
      mode: release

  next-version-hotfix:
    if: ${{ inputs.branch_type == 'hotfix' }}
    uses: KiTechSoftware/stability-flow/.github/workflows/next-version.yml@main
    with:
      mode: hotfix

  create-release-branch:
    if: ${{ inputs.branch_type == 'release' }}
    needs: [next-version]
    uses: KiTechSoftware/stability-flow/.github/workflows/create-release-branch.yml@main
    with:
      source_branch: ${{ inputs.source_branch }}
      identifier: ${{ inputs.identifier != '' && inputs.identifier || needs.next-version-release.outputs.next_version }}
      push_branch: true

  create-hotfix-branch:
    if: ${{ inputs.branch_type == 'hotfix' && inputs.auto_version_bump }}
    needs: [next-version-hotfix]
    uses: KiTechSoftware/stability-flow/.github/workflows/create-hotfix-branch.yml@main
    with:
      identifier: ${{ inputs.identifier != '' && inputs.identifier || needs.next-version-hotfix.outputs.next_version }}
      push_branch: true

  create-sync-branch:
    if: ${{ inputs.branch_type == 'sync' }}
    needs: [next-version]
    uses: KiTechSoftware/stability-flow/.github/workflows/create-sync-branch.yml@main
    with:
      identifier: ${{ inputs.identifier != '' && inputs.identifier || needs.next-version-release.outputs.current_version }}
      push_branch: true