name: Stability Flow

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - 'release/*'
      - 'hotfix/*'
      - 'sync/*'
      - 'wip/*'
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: read

jobs:
  pr-to-main:
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    uses: KiTechSoftware/stability-flow/.github/workflows/pr-to-main.yml@main
    with:
      source: ${{ github.head_ref }}
      target: ${{ github.base_ref }}
      title: ${{ github.event.pull_request.title }}
      format: markdown
      github-summary: true

  pr-to-develop:
    if: github.event_name == 'pull_request' && github.base_ref == 'develop'
    uses: KiTechSoftware/stability-flow/.github/workflows/pr-to-develop.yml@main
    with:
      source: ${{ github.head_ref }}
      title: ${{ github.event.pull_request.title }}
      allow_non_prefixed_branches_to_develop: true
      format: markdown
      github-summary: true

  release-branch:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'release/')
    uses: KiTechSoftware/stability-flow/.github/workflows/release-branch.yml@main
    with:
      branch: ${{ github.ref_name }}
      message: ${{ github.event.head_commit.message }}
      format: markdown
      github-summary: true

  hotfix-branch:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'hotfix/')
    uses: KiTechSoftware/stability-flow/.github/workflows/hotfix-branch.yml@main
    with:
      branch: ${{ github.ref_name }}
      message: ${{ github.event.head_commit.message }}
      format: markdown
      github-summary: true

  sync-branch:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'sync/')
    uses: KiTechSoftware/stability-flow/.github/workflows/sync-branch.yml@main
    with:
      branch: ${{ github.ref_name }}
      message: ${{ github.event.head_commit.message }}
      format: markdown
      github-summary: true

  wip-branch:
    if: github.event_name == 'push' && startsWith(github.ref_name, 'wip/')
    uses: KiTechSoftware/stability-flow/.github/workflows/wip-branch.yml@main
    with:
      branch: ${{ github.ref_name }}
      message: ${{ github.event.head_commit.message }}
      format: markdown
      github-summary: true