name: validate-pr-flow

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  validate:
    uses: KiTechSoftware/stability-flow/.github/workflows/validate-pr.yml@main
    with:
      source: ${{ github.head_ref }}
      target: ${{ github.base_ref }}
      title: ${{ github.event.pull_request.title }}
      format: text
      github-summary: true